
all: 1 2 3 4 5 6 7 8

clean:
	rm -f ./bin/1 ./bin/2 ./bin/3 ./bin/4 ./bin/5 ./bin/6 ./bin/7 ./bin/8

1: 1.c
	gcc -o ./bin/1 1.c -Wall

2: 2.c
	gcc -o ./bin/2 2.c -Wall

3: 3.c
	gcc -o ./bin/3 3.c -Wall

4: 4.c
	gcc -o ./bin/4 4.c -Wall

5: 5.c
	gcc -o ./bin/5 5.c -Wall

6: 6.c
	gcc -o ./bin/6 6.c -Wall

7: 7.c
	gcc -o ./bin/7 7.c -Wall

8: 8.c
	gcc -o ./bin/8 8.c -Wall

.PHONY: all clean 1 2 3 4 5 6 7 8
